name: TatanPGM
main: cl.eilers.tatanpoker09.Scrimmage
version: 0.01
description: A plugin for OCN-type Scrimmages.
author: tatanpoker09
authors: [pavilion99]
commands:
  setserver:
    description: Creates a server with its sign.
  setnext:
    description: Sets the next map.
  cycle:
    description: Cycles to the next map.
  cancel:
    description: Cancels the countdown.
  lobby:
    description: Teleports you to the lobby.
  join:
    description: Joins you to a team.
  start:
    description: Starts the match.
  end:
    description: Ends the match.
  g:
    description: Talks to general chat.
  maps:
    description: Lists all Loaded maps.
  setlobby:
    description: Sets world and coordenates as the new lobby.
  scrimmage:
    description: Teleports you to the current Scrimmage used map.